// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn6Gi-OBIEf3wa1GqzkCnW-9sD2-ah3k4',
    appId: '1:1034135324422:android:bb9cf6f220a87ae3e14087',
    messagingSenderId: '1034135324422',
    projectId: 'coden-testmode',
    storageBucket: 'coden-testmode.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOetGzxyRvFULLmghOKcIeuR7y3TE8RNM',
    appId: '1:1034135324422:ios:f9e7060be6d32d1de14087',
    messagingSenderId: '1034135324422',
    projectId: 'coden-testmode',
    storageBucket: 'coden-testmode.firebasestorage.app',
    androidClientId: '1034135324422-425fthf20ap3bnlgl2qq2tq90rmotuao.apps.googleusercontent.com',
    iosClientId: '1034135324422-1p407t9nfhluorfmg65lprji7q39c3c6.apps.googleusercontent.com',
    iosBundleId: 'com.testmee.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKIgz9epbC9aFkHUh4XZ45atnwkXGszbA',
    appId: '1:1034135324422:web:47da3fefa893ee5ce14087',
    messagingSenderId: '1034135324422',
    projectId: 'coden-testmode',
    authDomain: 'coden-testmode.firebaseapp.com',
    storageBucket: 'coden-testmode.firebasestorage.app',
    measurementId: 'G-27M0BZDLZR',
  );

}